version: 2

sources:
  - name: hospital_source
    catalog: "{{ target.catalog }}"
    schema: source
    tables:
      - name: diagnosis
      - name: patient
      - name: hospital
      - name: visit